"""Add user_id to customers

Revision ID: d8ebfb717d86
Revises: 52bc094b294a
Create Date: 2026-07-29 12:07:33.686373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8ebfb717d86'
down_revision: Union[str, Sequence[str], None] = '52bc094b294a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint('uq_customers_users_id', 'customers', ['user_id'])
    op.create_foreign_key('fk_customers_users_id', 'customers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_customers_users_id', 'customers', type_='foreignkey')
    op.drop_constraint('uq_customers_users_id', 'customers', type_='unique')
    op.drop_column('customers', 'user_id')
    # ### end Alembic commands ###
